version: 2
sources:
    - name: datafeed_shared_schema
      database: "{{('DBT_PRACTISE')}}"
      schema: STAGING
      tables:
        - name: raw_customer_data

        - name: raw_customer_order